//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Items
    {
        public int Order_Id { get; set; }
        public int Item_Id { get; set; }
        public int Product_Id { get; set; }
        public int Quantity { get; set; }
        public decimal List_Price { get; set; }
        public decimal Discount { get; set; }
    }
}
