//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Order_id { get; set; }
        public Nullable<int> Customer_id { get; set; }
        public byte Order_Status { get; set; }
        public System.DateTime Order_date { get; set; }
        public System.DateTime Required_date { get; set; }
        public Nullable<System.DateTime> Shipped_date { get; set; }
        public int Store_Id { get; set; }
        public int Staff_Id { get; set; }
    }
}
