//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Product_Id { get; set; }
        public string Product_Name { get; set; }
        public int Brand_Id { get; set; }
        public int Category_Id { get; set; }
        public short Model_Year { get; set; }
        public decimal List_Price { get; set; }
    }
}
